// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCatalogue.Data;

#nullable disable

namespace MovieCatalogue.Data.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6bde756c-dd87-48fe-a4de-7ee9a78779e4"),
                            MovieId = new Guid("7dc6c01d-68ed-475c-9ca1-3cda99437db2"),
                            UserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9")
                        },
                        new
                        {
                            Id = new Guid("82ca617c-5ad6-4487-943e-1caf0eea2a37"),
                            MovieId = new Guid("d4e6bf33-5a79-490a-89d1-dc9e2fe12b5c"),
                            UserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9")
                        },
                        new
                        {
                            Id = new Guid("adaafca9-2e3e-4853-9c34-67d511cf2e40"),
                            MovieId = new Guid("000a7d61-c851-4705-9e18-f16ea9624cf7"),
                            UserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016")
                        });
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2e80bd4-44f7-42f2-8a76-189fe9d12754"),
                            Name = "Drama"
                        },
                        new
                        {
                            Id = new Guid("5a5e5959-17ee-4b2a-8902-497a1c79321e"),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("d4a34098-333d-4177-9cbc-53a979f0382c"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("6f7c25cb-88f7-4036-902e-473b8b7f06d0"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("a8dbee99-43f7-4df1-824b-4b27600f67bd"),
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("947fa7e5-5013-4c8e-b03a-8e2aa6317cd8"),
                            Name = "Triller"
                        },
                        new
                        {
                            Id = new Guid("e692d3ba-17f1-466d-b8e5-aac14c4d8242"),
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("d5ce01d4-9ac0-411c-b813-e022d6886652"),
                            Name = "History"
                        },
                        new
                        {
                            Id = new Guid("ff41706e-522a-47cf-93e3-e646823ea7ed"),
                            Name = "Animation"
                        },
                        new
                        {
                            Id = new Guid("93df566f-30f5-4d2b-b6ff-dc540b86a289"),
                            Name = "Fantasy"
                        });
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<double>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2, 1)
                        .HasColumnType("float(2)")
                        .HasDefaultValue(0.0);

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a237ae5-bff5-4fa3-b30f-1303ea504903"),
                            Cast = "Daniel Radcliffe, Rupert Grint, Emma Watson, John Cleese, Robbie Coltrane, Warwick Davis, Richard Griffiths, Richard Harris, Ian Hart, John Hurt, Alan Rickman, Fiona Shaw, Maggie Smith, Julie Walters",
                            CreatedByUserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Description = "The story follows 11-year-old Harry Potter, who discovers on his birthday that he is a wizard. Raised by his cruel aunt and uncle, Harry learns that he is famous in the magical world for surviving an attack by the dark wizard Lord Voldemort, which left him with a lightning-shaped scar on his forehead. Harry is invited to attend Hogwarts School of Witchcraft and Wizardry, where he befriends Ron and Hermione. As they explore the mysteries of the school, they uncover a secret about the Philosopher's Stone, a magical object that grants immortality.",
                            Director = "Chris Columbus",
                            Duration = 152,
                            GenreId = new Guid("6f7c25cb-88f7-4036-902e-473b8b7f06d0"),
                            IsDeleted = false,
                            PosterUrl = "https://img.posterstore.com/zoom/wb0101-8harrypotter-thephilosophersstoneno150x70.jpg",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2001, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Harry Potter and the Philosopher's Stone",
                            TrailerUrl = "https://www.youtube.com/watch?v=VyHV0BRtdxo"
                        },
                        new
                        {
                            Id = new Guid("b1d07192-c121-443a-8367-b18934739a2e"),
                            Cast = "Ian McKellen, Martin Freeman, Richard Armitage, James Nesbitt, Ken Stott, Cate Blanchett, Ian Holm, Christopher Lee, Hugo Weaving, Elijah Wood, Andy Serkis",
                            CreatedByUserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Description = "TIn the peaceful Shire, Bilbo Baggins is visited by the wizard Gandalf (Ian McKellen) and a group of 13 dwarves, led by Thorin Oakenshield (Richard Armitage), who seek his help to reclaim the Lonely Mountain and its treasure, which has been overtaken by the fearsome dragon Smaug. Though Bilbo is initially reluctant to join their quest, he eventually agrees, setting off on an unexpected adventure that will take him across the dangerous and magical lands of Middle-earth.",
                            Director = "Peter Jackson",
                            Duration = 169,
                            GenreId = new Guid("6f7c25cb-88f7-4036-902e-473b8b7f06d0"),
                            IsDeleted = false,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTcwNTE4MTUxMl5BMl5BanBnXkFtZTcwMDIyODM4OA@@._V1_FMjpg_UX1000_.jpg",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2012, 11, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Hobbit: An Unexpected Journey",
                            TrailerUrl = "https://www.youtube.com/watch?v=9PSXjr1gbjc"
                        },
                        new
                        {
                            Id = new Guid("000a7d61-c851-4705-9e18-f16ea9624cf7"),
                            Cast = "Ben Affleck, Rosamund Pike, Neil Patrick Harris, Tyler Perry",
                            CreatedByUserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Description = "The story centers around the mysterious disappearance of Amy Dunne on the morning of her fifth wedding anniversary. As Nick becomes the prime suspect in her case, the investigation reveals troubling details about the couple's relationship. The film alternates between Nick's perspective and flashbacks through Amy's diary entries, gradually revealing a complex and twisted story of manipulation, deception, and psychological games.",
                            Director = "David Fincher",
                            Duration = 149,
                            GenreId = new Guid("947fa7e5-5013-4c8e-b03a-8e2aa6317cd8"),
                            IsDeleted = false,
                            PosterUrl = "https://m.media-amazon.com/images/I/61cdYGoHFrL._AC_SY879_.jpg",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2014, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gone Girl",
                            TrailerUrl = "https://www.youtube.com/watch?v=2-_-1nJf8Vg"
                        },
                        new
                        {
                            Id = new Guid("7dc6c01d-68ed-475c-9ca1-3cda99437db2"),
                            Cast = "Brad Pitt, Eric Bana, Orlando Bloom, Diane Kruger, Brian Cox, Sean Bean, Brendan Gleeson, Peter O'Toole",
                            CreatedByUserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Description = "The plot centers around the invasion of the city of Troy by the Greeks. The war is sparked when Paris, the prince of Troy, abducts Helen, the wife of Menelaus, the king of Sparta. In retaliation, Menelaus and his brother Agamemnon, the king of Mycenae, lead a Greek alliance to lay siege to Troy. The Greeks assemble an army that includes legendary warriors such as Achilles, the greatest of them all, and his rival Hector, the noble Trojan prince.",
                            Director = "Wolfgang Petersen",
                            Duration = 183,
                            GenreId = new Guid("d5ce01d4-9ac0-411c-b813-e022d6886652"),
                            IsDeleted = false,
                            PosterUrl = "https://www.rogerebert.com/wp-content/uploads/2024/03/Troy.jpg",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2004, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Troy",
                            TrailerUrl = "https://www.youtube.com/watch?v=znTLzRJimeY"
                        },
                        new
                        {
                            Id = new Guid("e8772d7c-8bda-4652-9f91-757857838db7"),
                            Cast = "Ray Romano, John Leguizamo, Denis Leary",
                            CreatedByUserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Description = "A gruff and solitary mammoth named Manny (voiced by Ray Romano) embarks on an unexpected journey when he crosses paths with Sid (voiced by John Leguizamo), a talkative sloth, and Diego (voiced by Denis Leary), a cunning saber-toothed tiger. Despite their differences, the trio is forced to work together when they discover a human infant. Manny, moved by a sense of duty, takes it upon himself to protect the baby and return it to its tribe. Along the way, the unlikely group faces numerous challenges, including predators hunting them, harsh environmental conditions, and natural obstacles, all while forging a bond that transcends their initial differences.",
                            Director = "Chris Wedge",
                            Duration = 81,
                            GenreId = new Guid("ff41706e-522a-47cf-93e3-e646823ea7ed"),
                            IsDeleted = false,
                            PosterUrl = "https://image.tmdb.org/t/p/original/idg7vYulQRXKEHfLIM0XKtqPkPz.jpg",
                            Rating = 4.0,
                            ReleaseDate = new DateTime(2003, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ice Age",
                            TrailerUrl = "https://www.youtube.com/watch?v=wjdqn9r4thg"
                        },
                        new
                        {
                            Id = new Guid("24e4cfc0-ec76-4f80-9d4c-e2f5bba1052e"),
                            Cast = "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez, Giovanni Ribisi",
                            CreatedByUserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Description = "The story follows Jake Sully (played by Sam Worthington), a paraplegic former Marine who is recruited to replace his deceased twin brother as an operator of an \"avatar\"—a remotely controlled, genetically engineered body that allows humans to interact with the indigenous Na'vi people on Pandora. The Na'vi are a humanoid species with blue skin and a deep connection to their environment. The human presence on Pandora is driven by the desire to mine a valuable mineral called unobtanium, which is found deep within the planet's forests.",
                            Director = "James Cameron",
                            Duration = 162,
                            GenreId = new Guid("93df566f-30f5-4d2b-b6ff-dc540b86a289"),
                            IsDeleted = false,
                            PosterUrl = "https://m.media-amazon.com/images/I/41kTVLeW1CL._AC_UF894,1000_QL80_.jpg",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar",
                            TrailerUrl = "https://www.youtube.com/watch?v=5PSNL1qE6VY"
                        },
                        new
                        {
                            Id = new Guid("d4e6bf33-5a79-490a-89d1-dc9e2fe12b5c"),
                            Cast = "Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson, Sally Field",
                            CreatedByUserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Description = "Forrest Gump tells the story of a simple man with a good heart who unintentionally influences major historical events and changes the lives of everyone he meets. From his humble beginnings in Alabama to becoming a war hero, a successful businessman, and a cultural icon, Forrest's journey is a testament to perseverance, love, and the power of kindness. At its core, the film explores themes of destiny, resilience, and the unpredictability of life.",
                            Director = "Robert Zemeckis",
                            Duration = 142,
                            GenreId = new Guid("c2e80bd4-44f7-42f2-8a76-189fe9d12754"),
                            IsDeleted = false,
                            PosterUrl = "https://static0.srcdn.com/wordpress/wp-content/uploads/2023/05/forrest-gump-movie-poster.jpg",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump",
                            TrailerUrl = "https://www.youtube.com/watch?v=bLvqoHBptjg"
                        },
                        new
                        {
                            Id = new Guid("47b1d1ca-756b-4f56-93ad-9d07c44d7b7a"),
                            Cast = "Matthew Broderick, James Earl Jones, Jeremy Irons, Nathan Lane, Rowan Atkinson, Whoopi Goldberg",
                            CreatedByUserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Description = "Simba, a young lion prince, must overcome adversity and reclaim his rightful place as king after the tragic death of his father, Mufasa. Along his journey, Simba learns about responsibility, love, and what it means to be a leader, all while confronting his wicked uncle, Scar, who has usurped the throne.",
                            Director = "Roger Allers, Rob Minkoff",
                            Duration = 88,
                            GenreId = new Guid("ff41706e-522a-47cf-93e3-e646823ea7ed"),
                            IsDeleted = false,
                            PosterUrl = "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRWwKdahmkJpbNfahOGIhiWjHl1UBLKCHOrqO3BLdR-zxHtGMXf1tjX28xeN30fBl-XXz3-AQ",
                            Rating = 4.0,
                            ReleaseDate = new DateTime(1994, 6, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lion King",
                            TrailerUrl = "https://www.youtube.com/watch?v=7TavVZMewpY"
                        },
                        new
                        {
                            Id = new Guid("31b7d9c1-b9b1-4a3e-9f71-d3d0fdbd94d2"),
                            Cast = "Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy, Cillian Murphy",
                            CreatedByUserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Description = "Dom Cobb, a thief with the ability to enter people's dreams and steal secrets, is offered a chance to have his criminal record erased if he can perform an inception—implanting an idea in someone's mind without their knowledge. Cobb assembles a team and dives deep into multiple layers of dreams, where time bends and the stakes are life or death.",
                            Director = "Christopher Nolan",
                            Duration = 148,
                            GenreId = new Guid("d4a34098-333d-4177-9cbc-53a979f0382c"),
                            IsDeleted = false,
                            PosterUrl = "https://cdn11.bigcommerce.com/s-yzgoj/images/stencil/1280x1280/products/2919271/5944675/MOVEB46211__19379.1679590452.jpg?c=2",
                            Rating = 4.0,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception",
                            TrailerUrl = "https://www.youtube.com/watch?v=YoHD9XEInc0"
                        },
                        new
                        {
                            Id = new Guid("7a59a1d2-d249-442a-8fbb-b3b4057e2e9d"),
                            Cast = "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine, Gary Oldman, Maggie Gyllenhaal",
                            CreatedByUserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Description = "Batman faces his greatest challenge when a criminal mastermind known as the Joker emerges from the shadows. As the Joker unleashes chaos on Gotham City, Batman must confront his own morals and the consequences of his actions, all while facing the growing tension between him and his trusted ally, Gotham City District Attorney Harvey Dent. With the fate of Gotham hanging in the balance, Batman must decide whether to uphold his code or take drastic action to save his city.",
                            Director = "Christopher Nolan",
                            Duration = 152,
                            GenreId = new Guid("d4a34098-333d-4177-9cbc-53a979f0382c"),
                            IsDeleted = false,
                            PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg",
                            Rating = 5.0,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/watch?v=EXeTwQWrcwY"
                        });
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasPrecision(2, 1)
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c9aa4a5-eb3c-4702-8ac7-f5325746a118"),
                            MovieId = new Guid("9a237ae5-bff5-4fa3-b30f-1303ea504903"),
                            UserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("d2449595-8786-4a6d-8ab9-e3afed8043d5"),
                            MovieId = new Guid("b1d07192-c121-443a-8367-b18934739a2e"),
                            UserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("ddd9ddcb-171a-4f34-8960-c18cdf26be08"),
                            MovieId = new Guid("000a7d61-c851-4705-9e18-f16ea9624cf7"),
                            UserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("e3ee90ed-5170-4712-be7d-e8d6619e5f9b"),
                            MovieId = new Guid("7dc6c01d-68ed-475c-9ca1-3cda99437db2"),
                            UserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("6f0b814d-c5ab-49d7-8853-316926625d53"),
                            MovieId = new Guid("e8772d7c-8bda-4652-9f91-757857838db7"),
                            UserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("a80f90a7-de2b-473b-97c2-d2e07d5e907d"),
                            MovieId = new Guid("24e4cfc0-ec76-4f80-9d4c-e2f5bba1052e"),
                            UserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("b968ef4d-e8aa-4fd7-bde7-6851ae882252"),
                            MovieId = new Guid("d4e6bf33-5a79-490a-89d1-dc9e2fe12b5c"),
                            UserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Value = 5
                        },
                        new
                        {
                            Id = new Guid("618011f7-19eb-4e26-a8dc-31bf947cd836"),
                            MovieId = new Guid("47b1d1ca-756b-4f56-93ad-9d07c44d7b7a"),
                            UserId = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("4fd3d72d-e12e-4f00-a898-5388e6e7b779"),
                            MovieId = new Guid("31b7d9c1-b9b1-4a3e-9f71-d3d0fdbd94d2"),
                            UserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Value = 4
                        },
                        new
                        {
                            Id = new Guid("226862a2-5137-463f-ab1a-a4008d1f5140"),
                            MovieId = new Guid("7a59a1d2-d249-442a-8fbb-b3b4057e2e9d"),
                            UserId = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            Value = 5
                        });
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatePosted")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2a82b11c-525b-44a4-9d03-a108c6bed3b9"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "de2a58fc-80e0-42b4-8f13-2cd90e19f663",
                            Email = "zhivko@movie.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ZHIVKO@MOVIE.COM",
                            NormalizedUserName = "ZHIVKO@MOVIE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFyQIcen0v1uq+q15mxr8w9IZNjJ5Gcnhj2PwOm142hnOHuSqylU/J9FyvX806tMcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9fd17910-ee48-4de9-9726-b34f62c48274",
                            TwoFactorEnabled = false,
                            UserName = "zhivko@movie.com"
                        },
                        new
                        {
                            Id = new Guid("ba09344d-675b-431b-9808-1b92c92ce016"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b846f7a-c56a-470d-99af-ec2477234ce4",
                            Email = "mitko@movie.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MITKO@MOVIE.COM",
                            NormalizedUserName = "MITKO@MOVIE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKtH7cNu8FtUCJsgSIFphqFNDmV3lBF/7jMGghmGdccOfeePS7/a5S1gO23f4SkycA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7a0214b9-5446-4aa5-a8f9-8c50de583da5",
                            TwoFactorEnabled = false,
                            UserName = "mitko@movie.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MovieCatalogue.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MovieCatalogue.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCatalogue.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MovieCatalogue.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Favorite", b =>
                {
                    b.HasOne("MovieCatalogue.Data.Models.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieCatalogue.Data.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Movie", b =>
                {
                    b.HasOne("MovieCatalogue.Data.Models.User", "CreatedByUser")
                        .WithMany("CreatedMovies")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCatalogue.Data.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Rating", b =>
                {
                    b.HasOne("MovieCatalogue.Data.Models.Movie", "Movie")
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieCatalogue.Data.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Review", b =>
                {
                    b.HasOne("MovieCatalogue.Data.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieCatalogue.Data.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.Movie", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MovieCatalogue.Data.Models.User", b =>
                {
                    b.Navigation("CreatedMovies");

                    b.Navigation("Favorites");

                    b.Navigation("Ratings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
